const {getLog} = require("../serverModules/logger");

/**
 * @openapi
 * /api/logs:
 *   get:
 *     summary: Retrieves the server's logs
 *     description: Returns a list of logs generated by the server.
 *     operationId: getLogs
 *     responses:
 *       200:
 *         description: A list of server logs.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: string
 *               description: Server logs
 */
module.exports = (req, res) => {
    res.json({ logs: getLog() });
};
